login screen
compsat/tanong-db pull request #8
Opened 2019-12-26 11:53 UTC by potetz

2019-12-26 11:58 UTC, potetz commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create landing page](https://trello.com/c/A88SvRgy/28-create-landing-page)

2019-12-28 13:12 UTC, daniddelrio requested changes
Nice to see you got the hang of Django even just a little bit! And good work also on the landing page; it looks neat :)) A few general comments lang:

1. Inline CSS is fine but I personally prefer using CSS files instead. I realized I forgot to teach you how to use CSS files in the Django environment, but I pushed some files to your branch to make things easier for you. Just add your CSS to database/static/database/css/main.css. If you wanna know how I set up the CSS, check my commit hehe
2. Maybe you can try using `form-control-sm` instead of `form-control` as I think the fields are too big? Or maybe adjust the padding of the fields by using [Bootstrap's built-in spacing utility classes](https://getbootstrap.com/docs/4.4/utilities/spacing/).
3. Use Roboto font like screens did! Just edit the main.css.

2019-12-28 13:12 UTC, daniddelrio commented on database/templates/database/.gitkeep
> +
Don't commit this file! I'm not sure what this file does HAHA

2019-12-28 13:12 UTC, daniddelrio commented on tanong_db/urls.py
> +    path('login/', views.login)
Don't remove the first two lines as these are meant to be in the `urls.py` of the main project.

`path('login/', views.login)` should be in the `urls.py` of our app folder, which is `database`, and not the urls.py of `tanong_db`.

2019-12-28 13:12 UTC, daniddelrio commented on tanong_db/views.py
> + return render(request, 'database/login.html')
This should also be in the `views.py` under `database`, not `tanong_db`! Typically the main project folder shouldn't contain a `views.py` file hehe

2020-01-03 04:43 UTC, daniddelrio approved these changes
Looks good to me! Comments lang for your future work:
1. Try to make your commit messages more informative so it'll easier to track the changes. [Read here](https://chris.beams.io/posts/git-commit/) on how to make good commit messages.
2. I recommend making the CSS for classes instead of IDs to increase reusability :)

2020-01-03 12:36 UTC, merged